// Package sub renders a user's 50 configs in every format clients ask for.
//
// Format selection is explicit-first: ?b64, ?raw, ?format=clash and /view all
// force a specific representation. Only a request with no format hint falls back
// to sniffing the Accept header. That ordering matters because a fair number of
// proxy clients send "Accept: */*", which is indistinguishable from a bare curl,
// so guessing must never be the only path to the right answer.
package sub

import (
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"

	"github.com/jack22Jqck211/panel/internal/proxyuri"
	"github.com/jack22Jqck211/panel/internal/store"
)

// Format is a subscription output representation.
type Format string

const (
	FormatBase64 Format = "base64"
	FormatRaw    Format = "raw"
	FormatHTML   Format = "html"
	FormatClash  Format = "clash"
)

// Raw joins the URIs with newlines: the plaintext subscription form.
func Raw(uris []string) string {
	return strings.Join(uris, "\n") + "\n"
}

// Base64 renders the standard base64 subscription body. Standard (padded)
// encoding is used because it is what the established clients accept.
func Base64(uris []string) string {
	return base64.StdEncoding.EncodeToString([]byte(strings.Join(uris, "\n")))
}

// UserInfoHeader builds the Subscription-Userinfo value clients read to display
// quota and expiry. The panel does not meter traffic, so the counters are
// reported as zero and only the limits carry information.
func UserInfoHeader(u *store.User) string {
	parts := []string{"upload=0", "download=0"}
	total := "0"
	if u.QuotaBytes > 0 {
		total = strconv.FormatInt(u.QuotaBytes, 10)
	}
	parts = append(parts, "total="+total)
	if !u.ExpiresAt.IsZero() {
		parts = append(parts, "expire="+strconv.FormatInt(u.ExpiresAt.Unix(), 10))
	}
	return strings.Join(parts, "; ")
}

// TitleHeader builds the Profile-Title value, base64 tagged so non-ASCII names
// survive transport.
func TitleHeader(name string) string {
	return "base64:" + base64.StdEncoding.EncodeToString([]byte(name))
}

// Clash renders a Clash-Meta / Mihomo configuration containing all 50 nodes and
// a selector group.
func Clash(cfgs []proxyuri.Config, uuid string, proto proxyuri.Protocol, title string) string {
	var b strings.Builder
	b.WriteString("# " + title + "\n")
	b.WriteString("# Generated by xray-tor-multiloc-panel\n\n")
	b.WriteString("mixed-port: 7890\n")
	b.WriteString("allow-lan: false\n")
	b.WriteString("mode: rule\n")
	b.WriteString("log-level: warning\n\n")
	b.WriteString("proxies:\n")

	names := make([]string, 0, len(cfgs))
	for _, c := range cfgs {
		name := c.Label
		names = append(names, name)
		b.WriteString("  - name: " + yamlQuote(name) + "\n")
		b.WriteString("    type: " + string(proto) + "\n")
		b.WriteString("    server: " + yamlQuote(c.Address) + "\n")
		b.WriteString("    port: " + strconv.Itoa(c.Port) + "\n")
		b.WriteString("    uuid: " + yamlQuote(uuid) + "\n")
		if proto == proxyuri.VMess {
			b.WriteString("    alterId: 0\n")
			b.WriteString("    cipher: auto\n")
		}
		b.WriteString("    udp: true\n")
		b.WriteString("    tls: " + strconv.FormatBool(c.TLS) + "\n")
		if c.TLS && c.Host != "" {
			b.WriteString("    servername: " + yamlQuote(c.Host) + "\n")
		}
		b.WriteString("    network: ws\n")
		b.WriteString("    ws-opts:\n")
		b.WriteString("      path: " + yamlQuote(c.Path) + "\n")
		if c.Host != "" {
			b.WriteString("      headers:\n")
			b.WriteString("        Host: " + yamlQuote(c.Host) + "\n")
		}
	}

	b.WriteString("\nproxy-groups:\n")
	b.WriteString("  - name: " + yamlQuote("Tor Locations") + "\n")
	b.WriteString("    type: select\n")
	b.WriteString("    proxies:\n")
	for _, n := range names {
		b.WriteString("      - " + yamlQuote(n) + "\n")
	}

	b.WriteString("\nrules:\n")
	b.WriteString("  - MATCH," + yamlQuote("Tor Locations") + "\n")
	return b.String()
}

// yamlQuote emits a double-quoted YAML scalar, escaping what must be escaped.
func yamlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}

// DetectFormat resolves the requested format. explicit carries the query
// parameters; accept is the raw Accept header.
func DetectFormat(hasB64, hasRaw, wantHTML bool, formatParam, accept string) Format {
	switch {
	case wantHTML:
		return FormatHTML
	case hasB64:
		return FormatBase64
	case hasRaw:
		return FormatRaw
	}
	switch strings.ToLower(strings.TrimSpace(formatParam)) {
	case "clash", "mihomo", "yaml":
		return FormatClash
	case "base64", "b64":
		return FormatBase64
	case "raw", "text", "plain":
		return FormatRaw
	case "html":
		return FormatHTML
	}
	// No hint given: a browser announces text/html, every known client does not.
	if strings.Contains(strings.ToLower(accept), "text/html") {
		return FormatHTML
	}
	return FormatBase64
}

// ContentType maps a format to its response content type.
func ContentType(f Format) string {
	switch f {
	case FormatHTML:
		return "text/html; charset=utf-8"
	case FormatClash:
		return "text/yaml; charset=utf-8"
	default:
		return "text/plain; charset=utf-8"
	}
}

// HumanBytes renders a byte count for display.
func HumanBytes(n int64) string {
	if n <= 0 {
		return "unlimited"
	}
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	units := []string{"KB", "MB", "GB", "TB", "PB"}
	v := float64(n)
	i := -1
	for v >= unit && i < len(units)-1 {
		v /= unit
		i++
	}
	return fmt.Sprintf("%.1f %s", v, units[i])
}
